# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCli2 < Formula
  desc ""
  homepage "https://github.com/jr-frazier/go-cli2"
  version "0.3.6"

  on_macos do
    url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.6/go-cli2_0.3.6_Darwin_all.tar.gz"
    sha256 "a5bbb9417c9f2610f23df3852ec6be7fe3762b3c97be16ce71550500ea63a4c3"

    def install
      bin.install "go-cli2"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.6/go-cli2_0.3.6_Linux_arm64.tar.gz"
      sha256 "b7ed381c3933fc4d408d46974ac24bffdcbf57ce5abcf9dcbd126919d0294745"

      def install
        bin.install "go-cli2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.6/go-cli2_0.3.6_Linux_x86_64.tar.gz"
      sha256 "e6b1b08d3e09ea8e45384f329b52744eaae36ed71707ccfe331f7fb13583ace5"

      def install
        bin.install "go-cli2"
      end
    end
  end
end
