# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocli2 < Formula
  desc ""
  homepage "https://github.com/jr-frazier/go-cli2"
  version "0.3.23"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.23/go-cli2_0.3.23_Darwin_arm64.tar.gz"
      sha256 "f521465666aa5527450e4cff33d6c8a79a451af1fea78d0f28db748f7b621f1f"

      def install
        bin.install "gocli2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.23/go-cli2_0.3.23_Darwin_x86_64.tar.gz"
      sha256 "5178803e31bb215d2e54b8799ed4d863c5feb5178927938e250a3932d57a0612"

      def install
        bin.install "gocli2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.23/go-cli2_0.3.23_Linux_x86_64.tar.gz"
      sha256 "14ae53a392f622291749b4b3568c90b721b49d0ca8265c2b33f06e7defd91a50"

      def install
        bin.install "gocli2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.23/go-cli2_0.3.23_Linux_arm64.tar.gz"
      sha256 "71ac2a6c3ef384b0ae667a75c48503bc0cb232329c3b57052c16c91192161d65"

      def install
        bin.install "gocli2"
      end
    end
  end
end
