# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gocli2 < Formula
  desc ""
  homepage "https://github.com/jr-frazier/go-cli2"
  version "0.3.30"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.30/go-cli2_0.3.30_Darwin_arm64.tar.gz"
      sha256 "77045f464e63f1e236e2bddd2578dcebac2c68e65e8cbf908ab7c5d60fe7b3cc"

      def install
        bin.install "gocli2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.30/go-cli2_0.3.30_Darwin_x86_64.tar.gz"
      sha256 "2cf807fb3cb3cef14b7c6d5d53a5ebaba5d200aebe21ce29356115999b0606fb"

      def install
        bin.install "gocli2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.30/go-cli2_0.3.30_Linux_x86_64.tar.gz"
      sha256 "08428f10a081ac680ef8061901b04983c0c0afc8d8d45dfe707dc19933f7b8db"

      def install
        bin.install "gocli2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-frazier/go-cli2/releases/download/v0.3.30/go-cli2_0.3.30_Linux_arm64.tar.gz"
      sha256 "d7cad8888ca831b461d1d6a53891c5502cbb443cbc8da1a1a63857431c08a31f"

      def install
        bin.install "gocli2"
      end
    end
  end
end
