# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PerfopsCli < Formula
  desc ""
  homepage "https://github.com/jr-frazier/perfops-cli"
  version "0.2.4"

  on_macos do
    url "https://github.com/jr-frazier/perfops-cli/releases/download/v0.2.4/perfops-cli_0.2.4_Darwin_all.tar.gz"
    sha256 "8a145d301cb8105da247c1137fa64f75253553525551579243d3d93c55feafe1"

    def install
      bin.install "perfops-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-frazier/perfops-cli/releases/download/v0.2.4/perfops-cli_0.2.4_Linux_arm64.tar.gz"
      sha256 "1bb40bc1698c0fcb52909c48f3b7f2cbfde801b2ad1beffacf5dc8a82ea781fa"

      def install
        bin.install "perfops-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jr-frazier/perfops-cli/releases/download/v0.2.4/perfops-cli_0.2.4_Linux_x86_64.tar.gz"
      sha256 "8bc747882899558505a671ba52e6f09e6d7be8f374e8fd6c5a5be0a4deba987c"

      def install
        bin.install "perfops-cli"
      end
    end
  end
end
