# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PerfopsCli < Formula
  desc ""
  homepage "https://github.com/jr-frazier/go-cli2"
  version "0.1.2"

  on_macos do
    url "https://github.com/jr-frazier/perfops-cli/releases/download/v0.1.2/perfops-cli_0.1.2_Darwin_all.tar.gz"
    sha256 "19d39a2aafb88db9057ecfe1c6624bf78f806e586354e2de856abcd06a31caf1"

    def install
      bin.install "perfops-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-frazier/perfops-cli/releases/download/v0.1.2/perfops-cli_0.1.2_Linux_arm64.tar.gz"
      sha256 "ad38c8d2a3013becb21b5c6eb44fc5fb318ff0c94d2bf70b896bf060917a74b0"

      def install
        bin.install "perfops-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jr-frazier/perfops-cli/releases/download/v0.1.2/perfops-cli_0.1.2_Linux_x86_64.tar.gz"
      sha256 "1a7ad317c56141bf7a8e25d548bb1a5e52a1ce111ad7fe61daf73957a94ef5f8"

      def install
        bin.install "perfops-cli"
      end
    end
  end
end
